export const customerRows = [
  {
    id: "acme",
    name: "Acme Corporation",
    email: "acme@dealflow360.demo",
    tier: "Gold",
    team: "Enterprise",
  },
  {
    id: "beta",
    name: "Beta Industries",
    email: "beta@dealflow360.demo",
    tier: "Silver",
    team: "Growth",
  },
  {
    id: "nova",
    name: "Nova Retail",
    email: "nova@dealflow360.demo",
    tier: "Bronze",
    team: "Growth",
  },
  {
    id: "zenith",
    name: "Zenith Co",
    email: "zenith@dealflow360.demo",
    tier: "Gold",
    team: "Enterprise",
  },
  {
    id: "delta",
    name: "Delta LLC",
    email: "delta@dealflow360.demo",
    tier: "Bronze",
    team: "Growth",
  },
  {
    id: "orion",
    name: "Orion Labs",
    email: "orion@dealflow360.demo",
    tier: "Gold",
    team: "Enterprise",
  },
  {
    id: "harbor",
    name: "Harbor Labs",
    email: "harbor@dealflow360.demo",
    tier: "Silver",
    team: "Enterprise",
  },
  {
    id: "northwind",
    name: "Northwind",
    email: "northwind@dealflow360.demo",
    tier: "Bronze",
    team: "Growth",
  },
];
export const productRows = [
  {
    id: "laptop",
    name: "Laptop Pro 14",
    category: "Hardware",
    priceCents: 120000,
    costCents: 78000,
    taxBps: 1500,
    stockable: true,
    intervalMonths: 0,
    variant: "14 inch",
    pairedProductIds: ["mouse", "dock", "care2"],
  },
  {
    id: "laptop13",
    name: "Laptop Pro 13",
    category: "Hardware",
    priceCents: 120000,
    costCents: 78000,
    taxBps: 1500,
    stockable: true,
    intervalMonths: 0,
    variant: "13 inch",
  },
  {
    id: "laptop16",
    name: "Laptop Pro 16",
    category: "Hardware",
    priceCents: 128000,
    costCents: 82000,
    taxBps: 1500,
    stockable: true,
    intervalMonths: 0,
    variant: "16 inch (+$80)",
  },
  {
    id: "dock",
    name: "Docking Station",
    category: "Hardware",
    priceCents: 18000,
    costCents: 9500,
    taxBps: 1500,
    stockable: true,
    intervalMonths: 0,
    variant: "Silver",
    promoted: true,
    promotionBps: 1200,
    pairedProductIds: ["monitoring"],
  },
  {
    id: "mouse",
    name: "Wireless Mouse",
    category: "Hardware",
    priceCents: 4000,
    costCents: 1200,
    taxBps: 1500,
    stockable: true,
    intervalMonths: 0,
    variant: "Standard",
  },
  {
    id: "setup",
    name: "Onsite Setup Service",
    category: "Services",
    priceCents: 45000,
    costCents: 32000,
    taxBps: 1000,
    stockable: false,
    intervalMonths: 0,
    variant: "Standard",
    pairedProductIds: ["warranty"],
  },
  {
    id: "warranty",
    name: "Extended Warranty",
    category: "Services",
    priceCents: 18000,
    costCents: 4000,
    taxBps: 1000,
    stockable: false,
    intervalMonths: 0,
    variant: "Standard",
  },
  {
    id: "care1",
    name: "Care Plan 1yr",
    category: "Subscription",
    priceCents: 2800,
    costCents: 800,
    taxBps: 0,
    stockable: false,
    intervalMonths: 1,
    variant: "Monthly",
  },
  {
    id: "care2",
    name: "Care Plan 2yr",
    category: "Subscription",
    priceCents: 4600,
    costCents: 1000,
    taxBps: 0,
    stockable: false,
    intervalMonths: 1,
    variant: "Monthly",
  },
  {
    id: "care3",
    name: "Care Plan Annual",
    category: "Subscription",
    priceCents: 40000,
    costCents: 9000,
    taxBps: 0,
    stockable: false,
    intervalMonths: 12,
    variant: "Yearly",
  },
  {
    id: "sla",
    name: "Support SLA",
    category: "Subscription",
    priceCents: 30000,
    costCents: 9000,
    taxBps: 0,
    stockable: false,
    intervalMonths: 3,
    variant: "Quarterly",
  },
  {
    id: "monitoring",
    name: "Monitoring Add-on",
    category: "Subscription",
    priceCents: 1500,
    costCents: 400,
    taxBps: 0,
    stockable: false,
    intervalMonths: 1,
    variant: "Monthly",
  },
];
